### ISSUE TITLE
Difference with s6-envdir -fn ?

### ISSUE THREAD

**Issue by skarnet** [just-containers/justc-envdir#1]
Hey @jprjr !
I'm wondering how `justc-envdir` differs from `s6-envdir -fn` and also if there's other functionality in my software that you'd like to have (in which case, if it's generic enough, it's better to have it upstream).
Cheers!

**Comment by jprjr** [comment]
Hey @skarnet ! Always good to hear from you!

It's mostly to address some issues that have been open for a while in s6-overlay wrt larger environment variables, like https://github.com/just-containers/s6-overlay/issues/212 and https://github.com/just-containers/s6-overlay/issues/46

Basically, there's a few features that would render this fork obsolete:

* No (or larger?) limit to reading the files. I just used one of the slurp functions. Ideally there should be some better sanity-checking there, maybe a flag to specify the max bytes.
* If a file is empty, add an empty variable instead of removing.
* No NULL-byte translation (instead, if a NULL is encountered, assume end-of-string). Maybe a flag like `-0`? (this seems like the least likely to be encountered)

I was looking into writing patches for s6 and skalibs, but I started thinking "man, this is introducing a lot of code paths." But I could take a crack at it, maybe it wouldn't be as complicated as I'm thinking.

**Comment by skarnet** [comment]
- Use the `openreadnclose()` function to specify a max amount of bytes.
- If 4096 is too small a limit, I can probably make it configurable in skalibs. There needs to be a reasonable limit though, because it's a user-provided file that's read into memory, and into the stack even, so yeah.
- I can probably accept `-c ""` to keep null characters verbatim, instead of rejecting it as it is now.
- However, when a file is empty, it removes the variable, that is API and I cannot change that without breaking a lot of things. A single newline is the way to declare an empty variable, it has always been like this, and I see no reason why s6-overlay cannot adapt to that.

**Comment by jprjr** [comment]
Regarding empty variables, s6-overlay uses `s6-dumpenv` to create the envdir which saves empty variables as empty files. Maybe `s6-dumpenv` could get a switch to translate empty variables into a newline?

Only issue there though, is then `s6-envdir -fn` will load that newline file as-is. Not sure what the right answer there is.

**Comment by skarnet** [comment]
Oh. What you're saying is that `s6-dumpenv` and `s6-envdir -fn` are not exact duals, because when you dump an empty variable, `s6-envdir -fn` will read it and remove the variable? Okay, that makes sense. I need to figure out a way to get perfect equivalence; will work on that.

**Comment by jprjr** [comment]
One idea: maybe they shouldn't be exact duals.

If I'm making an envdir for an app, like for `s6-tcpserver-access` to use, I'm going to write that out by hand, I can't think of a use where I'd want to programmatically save the entire environment and reload it with an envdir within the s6/daemontools ecosystem. I'm usually doing things like setting qmail environment variables.

Since `s6-dumpenv` doesn't make envdir's anyway, maybe the execline or portable-utils package could have a program that loads these directories as-is. Something like `loadenv` (in execline) or `s6-loadenv`. The manual for `s6-dumpenv` could be clarified that it's not suitable for making an envdir.

**Comment by skarnet** [comment]
Well the whole point was to make an envdir that is later readable by `s6-envdir -fn`. I didn't think people would need to dump and restore empty variables, so I ignored that case. You're saying that case is actually important. So I'm going to fix it.

**Comment by skarnet** [comment]
The current `s6-envdir` has all the needed options to accommodate all flavors of envdirs, including with unbounded variable size. Closing this.
